ludus:
  - vm_name: "{{ range_id }}-tpot"
    hostname: "{{ range_id }}-tpot"
    template: ubuntu-24.04-x64-server-template
    vlan: 100
    ip_last_octet: 10
    ram_gb: 8
    cpus: 4
    linux: true
    roles:
      - yudus.ludus_tpot_server

  - vm_name: "{{ range_id }}-esensor"
    hostname: "{{ range_id }}-esensor"
    template: ubuntu-24.04-x64-server-template
    vlan: 100
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    linux: true
    roles:
      - yudus.ludus_hiv_sensor
