# requirements.yml
- name: yudus.ludus_tpot_server
  src: git+https://github.com/TsamD/yudus.ludus_tpot_server.git

- name: yudus.ludus_hiv_sensor
  src: git+https://github.com/TsamD/yudus.ludus_hiv_sensor.git
