name: Deploy Range Config

on:
  push:
    paths:
      - 'ludus-range-config.yml'
      - 'roles/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Validate and Format YAML Config
      run: |
        echo "Validating YAML syntax (initial run)..."
        echo "config/ludus/ludus-range-config.yml"
        wget https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
        yq eval '...' ludus-range-config.yml

    - name: Install WireGuard & jq
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wireguard jq

    - name: Write WireGuard Config
      run
