name: Deploy Range Config

on:
  push:
    paths:
      - 'ludus-range-config.yml'
      - 'roles/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Validate and Format YAML Config
      run: |
        echo "🔍 Validating YAML syntax..."
        wget https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
        test -f ludus-range-config.yml || (echo "❌ Fichier non trouvé"; exit 1)
        yq eval '.' ludus-range-config.yml
        echo "✅ YAML validé."

    - name: Install WireGuard & jq
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wireguard jq

    - name: Write WireGuard Config
      run: |
        echo "$WIREGUARD_CONFIG" | base64 --decode > wg0.conf
        chmod 600 wg0.conf
        echo "✅ WireGuard config écrit."

      env:
        WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}

    - name: Activate WireGuard VPN
      timeout-minutes: 2
      run: |
        sudo wg-quick up ./wg0.conf
        echo "✅ VPN activé. Interface :"
        sudo wg show

    - name: Install Ludus CLI Non-Interactively
      run: |
        set -e
        if ! command -v script >/dev/null; then
          echo "❌ 'script' manquant"; exit 1
        fi
        script -q -c 'printf "y\ny\ny\n" | curl -s https://ludus.cloud/install | bash' /dev/null
      env:
        LUDUS_API_KEY: ${{ secrets.LUDUS_API_KEY }}

    - name: Validate Ludus API Key
      run: echo "✅ LUDUS_API_KEY est bien présent."
      env:
        LUDUS_API_KEY: ${{ secrets.LUDUS_API_KEY }}

    - name: Deploy Ludus Range
      run: |
        export LUDUS_API_KEY=${{ secrets.LUDUS_API_KEY }}
        ludus range config set -f ludus-range-config.yml
        ludus range deploy

    - name: Disconnect WireGuard
      run: sudo wg-quick down ./wg0.conf || echo "❗VPN déjà désactivé."
