name: Deploy Range Config

on:
  push:
    paths:
      - 'ludus-range-config.yml'
      - 'roles/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python, WireGuard, and Ludus CLI
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip wireguard
        pip3 install ludus-cli

    - name: Decode WireGuard config
      run: |
        echo "${{ secrets.WIREGUARD_CONFIG }}" | base64 -d > github-wg0.conf
        sudo mv github-wg0.conf /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf
        sudo wg-quick up wg0

    - name: Set Ludus API key
      run: echo "LUDUS_API_KEY=${{ secrets.LUDUS_API_KEY }}" >> $GITHUB_ENV

    - name: Deploy range
      run: |
        export LUDUS_API_KEY=${{ secrets.LUDUS_API_KEY }}
        ludus range config set -f ludus-range-config.yml
        ludus range deploy
