name: Deploy Range Config

on:
  push:
    paths:
      - 'ludus-range-config.yml'
      - 'roles/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode WireGuard config
      run: |
        echo "${{ secrets.WIREGUARD_CONFIG }}" | base64 -d > wg0.conf

    - name: Setup WireGuard and connect to server
      run: |
        sudo apt update
        sudo apt install -y wireguard
        sudo wg-quick up ./wg0.conf

    - name: Install Python and Ludus CLI
      run: |
        sudo apt install -y python3 python3-pip
        pip3 install ludus-cli

    - name: Set Ludus API key
      run: echo "LUDUS_API_KEY=${{ secrets.LUDUS_API_KEY }}" >> $GITHUB_ENV

    - name: Deploy range
      run: |
        export LUDUS_API_KEY=${{ secrets.LUDUS_API_KEY }}
        ludus range config set -f ludus-range-config.yml
        ludus range deploy
